### ISSUE TITLE
Undefined 'shelljoin' method failure on csslint dependency

### ISSUE THREAD

**Issue by ryancastle** [codeclimate/codeclimate#349]
Running latest image gives me this error. Docker promised me I would never have to see ruby dependency errors again, but they lied.

```
$ docker run   --interactive --tty --rm   --env CODE_PATH="$PWD"   --volume "$PWD":/code   --volume /var/run/docker.sock:/var/run/docker.sock   --volume /tmp/cc:/tmp/cc   codeclimate/codeclimate analyze
Starting analysis
Running brakeman: Done!
Running csslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine csslint failed with status 1 and stderr 
Unable to find image 'codeclimate/codeclimate-csslint:latest' locally
latest: Pulling from codeclimate/codeclimate-csslint
f5f17db9ef7c: Pulling fs layer
b323df73e6c4: Pulling fs layer
0fabb5fa5487: Pulling fs layer
a3ed95caeb02: Pulling fs layer
d9ccb0036cfb: Pulling fs layer
ec0a54bd51aa: Pulling fs layer
d60b871a6c06: Pulling fs layer
45e9f8b6dbef: Pulling fs layer
9bd4352dc82b: Pulling fs layer
bc45d97772cd: Pulling fs layer
a3ed95caeb02: Waiting
d9ccb0036cfb: Waiting
ec0a54bd51aa: Waiting
d60b871a6c06: Waiting
45e9f8b6dbef: Waiting
9bd4352dc82b: Waiting
bc45d97772cd: Waiting
0fabb5fa5487: Verifying Checksum
0fabb5fa5487: Download complete
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
f5f17db9ef7c: Verifying Checksum
f5f17db9ef7c: Download complete
f5f17db9ef7c: Pull complete
f5f17db9ef7c: Pull complete
d9ccb0036cfb: Verifying Checksum
d9ccb0036cfb: Download complete
ec0a54bd51aa: Verifying Checksum
ec0a54bd51aa: Download complete
b323df73e6c4: Verifying Checksum
b323df73e6c4: Download complete
b323df73e6c4: Pull complete
b323df73e6c4: Pull complete
0fabb5fa5487: Pull complete
0fabb5fa5487: Pull complete
a3ed95caeb02: Pull complete
a3ed95caeb02: Pull complete
d9ccb0036cfb: Pull complete
d9ccb0036cfb: Pull complete
ec0a54bd51aa: Pull complete
ec0a54bd51aa: Pull complete
9bd4352dc82b: Verifying Checksum
9bd4352dc82b: Download complete
45e9f8b6dbef: Verifying Checksum
45e9f8b6dbef: Download complete
d60b871a6c06: Verifying Checksum
d60b871a6c06: Download complete
d60b871a6c06: Pull complete
d60b871a6c06: Pull complete
45e9f8b6dbef: Pull complete
45e9f8b6dbef: Pull complete
9bd4352dc82b: Pull complete
9bd4352dc82b: Pull complete
bc45d97772cd: Verifying Checksum
bc45d97772cd: Download complete
bc45d97772cd: Pull complete
bc45d97772cd: Pull complete
Digest: sha256:71415c6acdd307c4775adedaacbbf0bd0aa5d66ada41eb87db52891dd62b17bf
Status: Downloaded newer image for codeclimate/codeclimate-csslint:latest
WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.3
/usr/src/app/lib/cc/engine/csslint.rb:65:in `csslint_xml': undefined method `shelljoin' for #<Array:0x00561ca2d51dc0> (NoMethodError)
	from /usr/src/app/lib/cc/engine/csslint.rb:61:in `results'
	from /usr/src/app/lib/cc/engine/csslint.rb:19:in `block in run'
	from /usr/src/app/lib/cc/engine/csslint.rb:18:in `chdir'
	from /usr/src/app/lib/cc/engine/csslint.rb:18:in `run'
	from /usr/src/app/bin/csslint:14:in `<main>'

```

**Comment by pbrisbin** [comment]
Oof, sorry about this. The Nokogiri warning is entirely unrelated. I made a
change recently to use shelljoin, and there must be a transitive require
that made it work in my tests but not your case. Probably just need to add
an explicit require in the file that uses it.

Unfortunately, I'm out of town, but hopefully a colleague of mine will see
this and make the easy fix soon.

**Comment by wfleming** [comment]
The fix for this has been released @ryancastle. Sorry about the issue. If you `docker pull codeclimate/codeclimate-csslint` to get the latest build, it should work.
