### ISSUE TITLE
Feature request: whitelist eslint-config-airbnb-base 

### ISSUE THREAD

**Issue by amercier** [codeclimate/codeclimate#428]
Airbnb [recently deprecated](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnbbase) `eslint-config-airbnb/base` in favor of `eslint-config-airbnb-base`:

> ### eslint-config-airbnb/base
> This entry point is deprecated. See eslint-config-airbnb-base.

Unfortunately, switching to `eslint-config-airbnb-base` fails in CodeClimate as it's not whitelisted:

```
/usr/src/app/node_modules/eslint/lib/config/config-file.js:336
            throw e;
            ^

Error: Cannot read config package: eslint-config-airbnb-base
Error: Cannot find module 'eslint-config-airbnb-base'
Referenced from: /code/.eslintrc
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadPackage (/usr/src/app/node_modules/eslint/lib/config/config-file.js:169:20)
    at loadConfigFile (/usr/src/app/node_modules/eslint/lib/config/config-file.js:216:18)
    at load (/usr/src/app/node_modules/eslint/lib/config/config-file.js:389:18)
    at /usr/src/app/node_modules/eslint/lib/config/config-file.js:330:36
    at Array.reduceRight (native)
    at applyExtends (/usr/src/app/node_modules/eslint/lib/config/config-file.js:313:28)
```

![screen shot 2016-05-06 at 10 05 30 am](https://cloud.githubusercontent.com/assets/1246795/15080298/3496c778-1372-11e6-8f0c-a35c8b74d6eb.png)

Could you add it to the [supported ESLint plugins](https://docs.codeclimate.com/docs/eslint#supported-plugins), please?

**Comment by pbrisbin** [comment]
Hi @amercier sorry about this. I'm going to move this issue over to [codeclimate/codeclimate-eslint](https://github.com/codeclimate/codeclimate-eslint). Let's pick up discussion there.

**Comment by amercier** [comment]
For reference: codeclimate/codeclimate-eslint#90
