### ISSUE TITLE
unexpected token at Mandatory arguments

### ISSUE THREAD

**Issue by MaurizioBella** [codeclimate/codeclimate#463]
Folks,
any thought on what I should do to figure out this error?
![codeclimaterun](https://cloud.githubusercontent.com/assets/17432412/16178586/0b664940-3623-11e6-89c9-d2cf196637f6.png)
following the list command and a couple of outputs.
![codeclimatelist](https://cloud.githubusercontent.com/assets/17432412/16178594/2a1503ae-3623-11e6-93f6-ee0be7c0fa65.png)
Docker on Windows7, default installation.
any insight would be appreciate.

**Comment by pbrisbin** [comment]
Hi, sorry for the trouble here. Can you try running with `--env CODECLIMATE_DEBUG=1`? That _should_ show the exact invocation we're using to run the apex engine and may shed some light.

**Comment by MaurizioBella** [comment]
@pbrisbin If you don't mind please don't close the issue since I'm not able to run the test until the end of this week. Apologize for that and appreciate your feedback.

**Comment by MaurizioBella** [comment]
@pbrisbin attached the output. Any thought? thanks
[logoutput.txt](https://github.com/codeclimate/codeclimate/files/333680/logoutput.txt)

**Comment by pbrisbin** [comment]
Thanks for the log @MaurizioBella, It looks a bit mangled so here's an attempt at cleaning it up a little:

```
$ docker run \
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD" \
  --env CODECLIMATE_DEBUG=1 \
  --volume "$PWD":/code \
  --volume /tmp/cc:/tmp/cc \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  codeclimate/codeclimate analyze
Starting analysis
[DEBUG] apexmetrics:stable engine config: {"enabled":true,"include_paths":[".bas h_history",".codeclimate.yml",".csslintrc",".docker/",".eslintignore",".eslintrc ",".gitconfig",".oracle_jre_usage/",".ssh/",".VirtualBox/",".zenmap/","apex-rule set.xml","AppData/","codeclimate/","Cookies","Dati applicazioni","Documenti","Im postazioni locali","Menu Avvio","Modelli","NTUSER.DAT","ntuser.dat.LOG1","ntuser .dat.LOG2","NTUSER.DAT{016888bd-6c6f-11de-8d1d-001e0bcde3ec}.TM.blf","NTUSER.DAT {016888bd-6c6f-11de-8d1d-001e0bcde3ec}.TMContainer00000000000000000001.regtrans- ms","NTUSER.DAT{016888bd-6c6f-11de-8d1d-001e0bcde3ec}.TMContainer000000000000000 00002.regtrans-ms","ntuser.ini","Recenti","Risorse di rete","Risorse di stampa", "ruleset.xml","salesforce/","SendTo","Tracing/"]}
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-apexmetrics-stable-4 127e567-b16e-4746-9923-1a60654c0bcb", "--cap-drop", "all", "--label", "com.codeclimate.label=5a5c0456-a26c-40af-9ec9-002b2897644d", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/c/Users/Maurizio:/cod e:ro", "--volume", "/tmp/cc/e56f5523-1e30-4ad3-92e2-88a47d321458:/config.json:ro ", "--user", "9000:9000", "codeclimate/codeclimate-apexmetrics"]
1) A java source code filename or directoryandatory arguments:
2) A report format
3) A ruleset filename or a comma-delimited string of ruleset filenames

For example:
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -d c:\my\source\code -f html -R java-unus
edcode

Languages and version suported:
apex

Available report formats and their configuration properties are:
   codeclimate: Code Climate integration.
   csv: Comma-separated values tabular format.
        problem - Include Problem column   default: true
        package - Include Package column   default: true
        file - Include File column   default: true
        priority - Include Priority column   default: true
        line - Include Line column   default: true
        desc - Include Description column   default: true
        ruleSet - Include Rule set column   default: true
        rule - Include Rule column   default: true
   emacs: GNU Emacs integration.
   html: HTML format
        linePrefix - Prefix for line number anchor in the source file.
        linkPrefix - Path to HTML source.
   ideaj: IntelliJ IDEA integration.
        classAndMethodName - Class and Method name, pass '.method' when processing a directory.   default:
        sourcePath - Source path.   default:
        fileName - File name.   default:
   summaryhtml: Summary HTML format.
        linePrefix - Prefix for line number anchor in the source file.
        linkPrefix - Path to HTML source.
   text: Text format.
   textcolor: Text format, with color support (requires ANSI console support, e.g. xterm, rxvt, etc.).
        color - Enables colors with anything other than 'false' or '0'.   default: yes
   textpad: TextPad integration.
   vbhtml: Vladimir Bossicard HTML format.
   xml: XML format.
        encoding - XML encoding format, defaults to UTF-8.   default: UTF-8
   xslt: XML with a XSL Transformation applied.
        encoding - XML encoding format, defaults to UTF-8.   default: UTF-8
        xsltFilename - The XSLT file name.
   yahtml: Yet Another HTML format.
        outputDir - Output directory.

For example on windows:
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -dir c:\my\source\code -format text -R java-unusedcode,java-imports -version 1.5 -language java -debug
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -dir c:\my\source\code -f xml -rulesets java-basic,java-design -encoding UTF-8
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -d c:\my\source\code -rulesets java-typeresolution -auxclasspath commons-collections.jar;derby.jar
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -d c:\my\source\code -f html -R java-typeresolution -auxclasspath file:///C:/my/classpathfile

For example on *nix:
$ pmd-bin-5.5.0-SNAPSHOT/bin/run.sh pmd -dir /home/workspace/src/main/java/code -f html -rulesets java-basic,java-design
$ pmd-bin-5.5.0-SNAPSHOT/bin/run.sh pmd -d ./src/main/java/code -f xslt -R java-basic,java-design -property xsltFilename=my-own.xsl
$ pmd-bin-5.5.0-SNAPSHOT/bin/run.sh pmd -d ./src/main/java/code -f html -R java-typeresolution -auxclasspath commons-collections.jar:derby.jar
error: (JSON::ParserError) 757: unexpected token at 'Mandatory arguments:
1) A java source code filename or directory
2) A report format
3) A ruleset filename or a comma-delimited string of ruleset filenames

For example:
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -d c:\my\source\code -f html -R java-unusedcode

Languages and version suported:
apex

Available report formats and their configuration properties are:
   codeclimate: Code Climate integration.
   csv: Comma-separated values tabular format.
        problem - Include Problem column   default: true
        package - Include Package column   default: true
        file - Include File column   default: true
        priority - Include Priority column   default: true
        line - Include Line column   default: true
        desc - Include Description column   default: true
        ruleSet - Include Rule set column   default: true
        rule - Include Rule column   default: true
   emacs: GNU Emacs integration.
   html: HTML format
        linePrefix - Prefix for line number anchor in the source file.
        linkPrefix - Path to HTML source.
   ideaj: IntelliJ IDEA integration.
        classAndMethodName - Class and Method name, pass '.method' when processing a directory.   default:
        sourcePath - Source path.   default:
        fileName - File name.   default:
   summaryhtml: Summary HTML format.
        linePrefix - Prefix for line number anchor in the source file.
        linkPrefix - Path to HTML source.
   text: Text format.
   textcolor: Text format, with color support (requires ANSI console support, e.g. xterm, rxvt, etc.).
        color - Enables colors with anything other than 'false' or '0'.   default: yes
   textpad: TextPad integration.
   vbhtml: Vladimir Bossicard HTML format.
   xml: XML format.
        encoding - XML encoding format, defaults to UTF-8.   default: UTF-8
   xslt: XML with a XSL Transformation applied.
        encoding - XML encoding format, defaults to UTF-8.   default: UTF-8
        xsltFilename - The XSLT file name.
   yahtml: Yet Another HTML format.
        outputDir - Output directory.

For example on windows:
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -dir c:\my\source\code -format text -R java-unusedcode,java-imports -version 1.5 -language java -debug
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -dir c:\my\source\code -f xml -rulesets java-basic,java-design -encoding UTF-8
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -d c:\my\source\code -rulesets java-typeresolution -auxclasspath commons-collections.jar;derby.jar
C:\>pmd-bin-5.5.0-SNAPSHOT\bin\pmd.bat -d c:\my\source\code -f html -R java-typeresolution -auxclasspath file:///C:/my/classpathfile

For example on *nix:
$ pmd-bin-5.5.0-SNAPSHOT/bin/run.sh pmd -dir /home/workspace/src/main/java/code -f html -rulesets java-basic,java-design
$ pmd-bin-5.5.0-SNAPSHOT/bin/run.sh pmd -d ./src/main/java/code -f xslt -R java-basic,java-design -property xsltFilename=my-own.xsl
$ pmd-bin-5.5.0-SNAPSHOT/bin/run.sh pmd -d ./src/main/java/code -f html -R java-typeresolution -auxclasspath commons-collections.jar:derby.jar



        /usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
'       /usr/src/app/lib/cc/analyzer/issue.rb:50:in `parsed_output'
[DEBUG] /usr/src/app/lib/cc/analyzer/issue.rb:21:in `as_json'ib/json/common.rb:155:in `p/usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/json/encodi/usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/json/encodi/usr/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/core_ext/ob/usr/src/app/lib/cc/analyzer/engine_output.rb:5:in `to_json'
        /usr/src/app/lib/cc/analyzer/container.rb:115:in `call'run'
        /usr/src/app/lib/cc/analyzer/container.rb:112:in `each_line'evels) in read_stdou/usr/src/app/lib/cc/analyzer/container.rb:112:in `block in read_stdout'

Maurizio@Maurizio-VAIO MINGW64 ~
$
```

Nothing immediately jumped out at me, except that there are files in the include-paths with spaces in them. One possibility is the apex engine doesn't handle that well and is incorrectly interpretting them being passed on a commandline invocation somewhere.

I'll have to dig in a bit more tomorrow.

/cc @mrb

**Comment by MaurizioBella** [comment]
@pbrisbin thanks for dropping me your note. I've tried to run from an empty path without all those directories.
here you are
[logoutput.txt](https://github.com/codeclimate/codeclimate/files/333899/logoutput.txt)

**Comment by MaurizioBella** [comment]
@mrb @pbrisbin any though please?

**Comment by pbrisbin** [comment]
@MaurizioBella I've tried to repruce this, but am unable. Can you please send or link me a tar archive of an example project that produces this issue for you? So I can be sure I'm testing the same code.

```
% ls -l
total 4
-rw-r--r-- 1 patrick patrick   0 Jul  8 09:52 Foo.cls
-rw-r--r-- 1 patrick patrick 373 Jul  8 09:53 ruleset.xml
% cat .codeclimate.yml 
engines:
  apexmetrics:
    enabled: true
% cat ruleset.xml 
<rule ref="rulesets/apex/complexity.xml/ExcessiveClassLength" message="Whatever">
  <priority>3</priority>
  <properties>
    <property name="minimum" value="1000"/>
    <property name="cc_remediation_points_multiplier" value="150"/>
    <property name="cc_categories" value="Complexity"/>
    <property name="cc_block_highlighting" value="false"/>
  </properties>
</rule>
% codeclimate analyze
Starting analysis
Running apexmetrics: Done!

Analysis complete! Found 0 issues.
```

**Comment by MaurizioBella** [comment]
@pbrisbin  I don't know why but I suppose I've some problem with the docker codeclimate at all
attached the file.
[docker.txt](https://github.com/codeclimate/codeclimate/files/355783/docker.txt)
I'm trying with Debian or other SO. appreciate your help

**Comment by MaurizioBella** [comment]
yes the problem was on windows, with debian works perfectly. thanks @pbrisbin
