### ISSUE TITLE
error: (CC::Analyzer::Engine::EngineTimeout) engine apexmetrics:stable ran for 900 seconds and was killed

### ISSUE THREAD

**Issue by MaurizioBella** [codeclimate/codeclimate#471]
Hi there!
I've opened the issue on the the relative engine but they asked me to post over here
https://github.com/Up2Go/codeclimate-apexmetrics/issues/39
attached the previous output as well.
[apexmetricsEngineTimeout.txt](https://github.com/codeclimate/codeclimate/files/368062/apexmetricsEngineTimeout.txt)

appreciate for any thought.

  ```
  mauri@debianvb:~/Documents/codeclimate/apexmetrics$ sudo codeclimate analyze
[sudo] password for mauri: 
Starting analysis
Running apexmetrics: Done!
error: (CC::Analyzer::Engine::EngineTimeout) engine apexmetrics:stable ran for 900 seconds and was killed
mauri@debianvb:~/Documents/codeclimate/apexmetrics$ 
mauri@debianvb:~/Documents/codeclimate/apexmetrics$ find .
.
./.codeclimate.yml
./analyze
./analyze/OpportunityLineItemTrigger.trigger
./analyze/OpportunityTrigger.trigger
mauri@debianvb:~/Documents/codeclimate/apexmetrics$ cat ./.codeclimate.yml 
engines:
  apexmetrics:
    enabled: true
ratings:
  paths:
    - "**.cls"
    - "**.trigger"

  ```

**Comment by pbrisbin** [comment]
Hey sorry for the trouble here. Are you able to run the apex tool directly (not as an engine or via codeclimate) to see if it indeed takes longer than 15 minutes on your source code?

Also, please provide output when run with `CODECLIMATE_DEBUG=1` as well as some general system information like `docker version` or `uname -a`. Thanks.

**Comment by MaurizioBella** [comment]
@pbrisbin thanks for all your thought on that. here you are:

```
mauri@debianvb:~/Documents/codeclimate/apexmetrics$ sudo CODECLIMATE_DEBUG=1 codeclimate analyze
Starting analysis
[DEBUG] apexmetrics:stable engine config: {"enabled":true,"include_paths":[".codeclimate.yml","analyze/"]}
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-apexmetrics-stable-62b8dbdc-6112-4fc7-a41d-0539c0269ae0", "--cap-drop", "all", "--label", "com.codeclimate.label=ee959036-a2e4-43cc-932b-6e67f7cba326", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/home/mauri/Documents/codeclimate/apexmetrics:/code:ro", "--volume", "/tmp/cc/56da097f-c3bb-458f-97a3-592bcdde883d:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-apexmetrics"]
error: (CC::Analyzer::Engine::EngineTimeout) engine apexmetrics:stable ran for 900 seconds and was killed
[DEBUG] backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:14:in `timed_out'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `block in timed_out'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `timed_out'
	/usr/src/app/lib/cc/analyzer/container.rb:71:in `run'
	/usr/src/app/lib/cc/analyzer/engine.rb:52:in `run'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:60:in `block in run_engine'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:74:in `with_spinner'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:55:in `block in engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:18:in `engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:54:in `engine_running'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:59:in `run_engine'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `block in run'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `each'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
	/usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
	/usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
	/usr/src/app/lib/cc/cli/command.rb:24:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:22:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:8:in `run'
	/usr/src/app/bin/codeclimate:6:in `<main>'
mauri@debianvb:~/Documents/codeclimate/apexmetrics$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
mauri@debianvb:~/Documents/codeclimate/apexmetrics$ uname -a
Linux debianvb 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
mauri@debianvb:~/Documents/codeclimate/apexmetrics$ 
```

**Comment by pbrisbin** [comment]
Sorry for the delayed response here. Are you able to run the apex tool directly (not as an engine or via codeclimate) to see if it indeed takes longer than 15 minutes on your source code?

I'd like to figure out if the time is being taken by our code in the engine, or the underlying tool itself.

**Comment by MaurizioBella** [comment]
thanks @pbrisbin for coming back to me. 
The PMD on Eclipse works fine, taking a short time (less than 15m) to send me back the result.

**Comment by pbrisbin** [comment]
Hmm. OK, that indicates to me that the bug is in the engine. I believe the Issue you originally opened there is the appropriate place, since this is unlikely to be the fault of the CLI itself. I would encourage you to ask that it be re-opened, but I appreciate how annoying it is to be bounced back and forth.

Either way, would you be willing to share a tar archive of a minimal project that exhibits this issue? It's probably the only way we'll be able to reproduce and debug the issue further. Thanks.

**Comment by MaurizioBella** [comment]
@pbrisbin I understand and not a problem at all. 
As soon as I can I'll share the tar. Please feel free to close this issue
appreciate for your help on that.

**Comment by pbrisbin** [comment]
Thanks very much for your understanding.
