### ISSUE TITLE
Codeclimate wrapper script appears to not respect exclude_paths

### ISSUE THREAD

**Issue by ehannes** [codeclimate/codeclimate#511]
Running with docker directly works fine:
```
docker run \
>   --interactive --tty --rm \
>   --env CODECLIMATE_CODE="/code" \
>   --volume "$PWD":/code \
>   --volume /var/run/docker.sock:/var/run/docker.sock \
>   --volume /tmp/cc:/tmp/cc \
>   codeclimate/codeclimate analyze . -e duplication
Starting analysis
Running duplication: Done!
```
Runnig with wrapper script does not respect `exclude_paths`:
```
CODECLIMATE_DEBUG=1 codeclimate analyze . -e duplication
[DEBUG] Couldn't include because part of path doesn't exist. path="./."
Starting analysis
[DEBUG] duplication:stable engine config: {"enabled":true,"config":{"languages":["ruby","javascript"]},"exclude_paths":["vendor"],"include_paths":["./"]}
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-duplication-stable-0429f479-c6f1-4ef9-9868-0b5f5854c670", "--cap-drop", "all", "--label", "com.codeclimate.label=3bf99c91-29b9-4246-9804-c01dc4f3f
559", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/home/hannes/workspaces/myproject:/code:ro", "--volume", "/tmp/cc/8d35fc70-ac25-43b3-95cc-4a24db4ba7c7:/co
nfig.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-duplication"]
```
...followed by several thousand lines of code and then this at the end:
```
...
Processing ./vendor/assets/bower_components/moment/src/lib/create/valid.js
Processing ./vendor/assets/bower_components/moment/src/lib/format/format.js
Skipping file ./vendor/assets/bower_components/moment/min/locales.min.js because the file is minified
Skipping file ./vendor/assets/bower_components/moment/min/moment.min.js because the file is minified
Processing ./vendor/assets/bower_components/moment/min/moment-with-locales.js
Error: Your application used more memory than the safety cap of 500M.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace
[DEBUG] backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `block in finished'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `each'
        /usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `finished'
        /usr/src/app/lib/cc/analyzer/container.rb:78:in `run'
        /usr/src/app/lib/cc/analyzer/engine.rb:52:in `run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:60:in `block in run_engine'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:60:in `with_spinner'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:41:in `block in engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/formatter.rb:29:in `engine_running'
        /usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:40:in `engine_running'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:59:in `run_engine'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `block in run'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `each'
        /usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `run'
        /usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
        /usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
        /usr/src/app/lib/cc/cli/command.rb:24:in `execute'
        /usr/src/app/lib/cc/cli/runner.rb:22:in `run'
        /usr/src/app/lib/cc/cli/runner.rb:8:in `run'
        /usr/src/app/bin/codeclimate:6:in `<main>'
```
```
$ uname -a
Linux zenbook-ubuntu 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```
`env | grep "^DOCKER_"` gives nothing.

**Comment by wfleming** [comment]
Hi @ehannes,

Sorry for the trouble here. I see a couple things to try:

1. I suggest not putting the `.` path in your invocation when you run analysis: specifying a path to analyze on the command line currently overrides/ignores all exclude paths, so I would not expect any exclude paths to get applied with that argument there. Without a path provided, the CLI will analyze the whole project (except the exclude paths), so you don't need to provide it. For future reference, there's currently a quirk in our path-processing code that doesn't like leading `.`s, so if you did want to analyze a subdirectory or a specific file, you'd want to run `codeclimate analyze foo/bar`, not `codeclimate analyze `./foo/bar`.

2. If you're still seeing different behavior after removing that argument, could you please add `--env CODECLIMATE_DEBUG=1` to your explicit `docker run` invocation? That would show more of the same debug output around what paths were generated & how engines were run, which would help identify how these invocations are behaving differently.

Let me know how that goes.

**Comment by ehannes** [comment]
Perfect! Removing the `.` made it work! Thanks for the quick reply!
