### ISSUE TITLE
CC engine structure failed with status 1 and stderr 

### ISSUE THREAD

**Issue by Edvinas-Matulaitis** [codeclimate/codeclimate#853]
Few days ago installed codeclimate locally on OSX. Everything was fine and I was running analyze like this perfectly:

`codeclimate analyze src/service/v2/test/test.php`

Today I get this error with same command

```
Starting analysis
Running structure: Done!
error: (CC::CLI::Analyze::EngineFailure) engine structure failed with status 1 and stderr 
12
Parser process id: 12
codeclimate-parser socket not present
waiting 1s...
/home/app/codeclimate-structure/lib/cc/engine/structure.rb:10:in `require': cannot load such file -- cc/parser (LoadError)
	from /home/app/codeclimate-structure/lib/cc/engine/structure.rb:10:in `<top (required)>'
	from bin/structure:6:in `require'
	from bin/structure:6:in `<main>'
```
Engines are installed, codeclimate updated to newest version. Here is same command with debug option enabled:

```
I, [2018-07-04T09:38:03.916878 #1]  INFO -- : starting engine structure
D, [2018-07-04T09:38:03.931685 #1] DEBUG -- : /config.json content: {"enabled"=>true, "channel"=>"stable", "include_paths"=>["src/service/v2/test/test.php"], "debug"=>"1"}
D, [2018-07-04T09:38:03.943920 #1] DEBUG -- : docker run: ["docker", "run", "--name", "cc-engines-structure-stable-832dafee-40aa-4e83-bd8d-994619e84a4d", "--cap-drop", "all", "--label", "com.codeclimate.label=4785e408-22ff-4385-90f6-82fbc4b95600", "--log-driver", "none", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/Users/edvinas/develop/sites/site/html/sitel:/code:ro", "--volume", "/tmp/cc/4f457618-26a3-498c-8e2c-720705fd446c:/config.json:ro", "--user", "9000:9000", "--memory", "1024000000", "codeclimate/codeclimate-structure"]
D, [2018-07-04T09:38:04.379480 #1] DEBUG -- : engine stderr: 12
D, [2018-07-04T09:38:04.379613 #1] DEBUG -- : engine stderr: Parser process id: 12
D, [2018-07-04T09:38:04.380207 #1] DEBUG -- : engine stderr: codeclimate-parser socket not present
D, [2018-07-04T09:38:04.380290 #1] DEBUG -- : engine stderr: waiting 1s...
D, [2018-07-04T09:38:05.730748 #1] DEBUG -- : engine stderr: /home/app/codeclimate-structure/lib/cc/engine/structure.rb:10:in `require': cannot load such file -- cc/parser (LoadError)
D, [2018-07-04T09:38:05.730849 #1] DEBUG -- : engine stderr: 	from /home/app/codeclimate-structure/lib/cc/engine/structure.rb:10:in `<top (required)>'
D, [2018-07-04T09:38:05.730904 #1] DEBUG -- : engine stderr: 	from bin/structure:6:in `require'
D, [2018-07-04T09:38:05.730943 #1] DEBUG -- : engine stderr: 	from bin/structure:6:in `<main>'
I, [2018-07-04T09:38:06.122038 #1]  INFO -- : finished engine structure
error: (CC::CLI::Analyze::EngineFailure) engine structure failed with status 1 and stderr 
12
Parser process id: 12
codeclimate-parser socket not present
waiting 1s...
/home/app/codeclimate-structure/lib/cc/engine/structure.rb:10:in `require': cannot load such file -- cc/parser (LoadError)
	from /home/app/codeclimate-structure/lib/cc/engine/structure.rb:10:in `<top (required)>'
	from bin/structure:6:in `require'
	from bin/structure:6:in `<main>'
D, [2018-07-04T09:38:06.122261 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `block in finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `finished'
	/usr/src/app/lib/cc/analyzer/bridge.rb:52:in `block (2 levels) in run'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:63:in `with_spinner'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:41:in `block in engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:31:in `engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:40:in `engine_running'
	/usr/src/app/lib/cc/analyzer/bridge.rb:37:in `block in run'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `each'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:36:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'

```

Any ideas how it stopped working after few days?

**Comment by Edvinas-Matulaitis** [comment]
Solved issue removing codeclimate docker image and structure image with those:

```
docker rmi codeclimate/codeclimate
docker rmi codeclimate/codeclimate-structure
```

and then installing them back:

`codeclimate engines:install`
