### ISSUE TITLE
Errors: Bad gateway or gateway not responding (CC::Parser::Client::HTTPError)

### ISSUE THREAD

**Issue by mskogorevrmc** [codeclimate/codeclimate#968]
Wasn't entirely sure where to report this, it's specific to the js/php parser used by the structure and duplication engines. Feel free to transfer this issue to a more appropriate repository.

We've been using CodeClimate for a bit with our large codebase and noticed the engines were throwing some parser errors:

```
12
Parser process id: 12
codeclimate-parser socket not present
waiting 1s...
/home/app/.rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.0/lib/concurrent/atomic/mutex_atomic_fixnum.rb:80: warning: constant ::Fixnum is deprecated
W, [2020-08-11T10:20:14.939241 #1]  WARN -- : Skipping ./htdocs/js/angular/angular.min.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:15.039117 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:15.539480 #1]  WARN -- : Skipping ./htdocs/js/angular/angular.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:15.639664 #1]  WARN -- : Response status: 413
W, [2020-08-11T10:20:16.440494 #1]  WARN -- : Skipping ./htdocs/js/jquery.tinysort.min.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:16.540533 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:17.326274 #1]  WARN -- : Skipping ./htdocs/js/date.min.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:17.328992 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:21.631405 #1]  WARN -- : Skipping ./htdocs/js/js-ofc-library/open_flash_chart.min.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:21.731455 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:22.513867 #1]  WARN -- : Skipping ./htdocs/js/swfobject.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:22.612674 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:27.191916 #1]  WARN -- : Skipping ./htdocs/js/select2/select2.min.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:27.191977 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:28.693985 #1]  WARN -- : Skipping ./htdocs/js/jquery-ui/jquery-ui-1.12.1.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:28.722925 #1]  WARN -- : Response status: 413
W, [2020-08-11T10:20:28.821617 #1]  WARN -- : Skipping ./htdocs/js/clipboard.min.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:28.821674 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:30.685566 #1]  WARN -- : Skipping ./htdocs/js/ipaddr.min.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:30.785585 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:31.076373 #1]  WARN -- : Skipping ./htdocs/js/jquery.mCustomScrollbar.min.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:31.076433 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:32.028488 #1]  WARN -- : Skipping ./htdocs/js/no_vnc/v1_10/web-socket-js/swfobject.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:32.028543 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:32.087587 #1]  WARN -- : Skipping ./htdocs/js/no_vnc/v1_10/keysymdef.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:32.087906 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:32.259912 #1]  WARN -- : Skipping ./htdocs/js/no_vnc/v1_10/logo.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:32.259984 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:33.459807 #1]  WARN -- : Skipping ./htdocs/js/no_vnc/web-socket-js/swfobject.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:33.460308 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:33.863855 #1]  WARN -- : Skipping ./htdocs/js/no_vnc/logo.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:33.866601 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:20:33.947586 #1]  WARN -- : Skipping ./htdocs/js/charts.js due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:34.025932 #1]  WARN -- : Response status: 422
/home/app/.rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.0/lib/concurrent/atomic/mutex_atomic_fixnum.rb:80: warning: constant ::Fixnum is deprecated
W, [2020-08-11T10:20:44.352743 #1]  WARN -- : Skipping ./rmc_app/views/cloud/vpn_settings_view.php due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:20:44.352781 #1]  WARN -- : Response status: 422
W, [2020-08-11T10:21:04.157963 #1]  WARN -- : Skipping ./rmc_app/libraries/pdf/tcpdf/fonts/cid0ct.php due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:21:04.258007 #1]  WARN -- : Response status: 413
W, [2020-08-11T10:21:04.641839 #1]  WARN -- : Skipping ./rmc_app/libraries/pdf/tcpdf/fonts/cid0kr.php due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:21:04.642408 #1]  WARN -- : Response status: 413
W, [2020-08-11T10:21:29.322002 #1]  WARN -- : Skipping ./rmc_app/libraries/pdf/tcpdf/fonts/cid0jp.php due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:21:29.422042 #1]  WARN -- : Response status: 413
W, [2020-08-11T10:22:01.793653 #1]  WARN -- : Skipping ./rmc_app/libraries/pdf/tcpdf/fonts/cid0cs.php due to CC::Parser::Client::HTTPError
W, [2020-08-11T10:22:01.893222 #1]  WARN -- : Response status: 413
E, [2020-08-11T10:22:25.081531 #1] ERROR -- : Error processing file: ./rmc_app/libraries/pdf/tcpdf/fonts/dejavusanscondensedbi.php
E, [2020-08-11T10:22:25.081653 #1] ERROR -- : (502) Bad gateway or gateway not responding
I, [2020-08-11T10:22:25.081714 #1]  INFO -- : CC::Parser::Client::HTTPError error occurred processing file ./rmc_app/libraries/pdf/tcpdf/fonts/dejavusanscondensedbi.php: aborting.
W, [2020-08-11T10:22:25.081758 #1]  WARN -- : Error processing file: ./rmc_app/libraries/pdf/tcpdf/fonts/dejavusanscondensedbi.php
#<Thread:0x00007f3cc4c3c410@/usr/src/app/lib/cc/engine/analyzers/file_thread_pool.rb:22 run> terminated with exception (report_on_exception is true):
/home/app/codeclimate-parser-client/lib/cc/parser/client.rb:86:in `run': (502) Bad gateway or gateway not responding (CC::Parser::Client::HTTPError)
	from /home/app/codeclimate-parser-client/lib/cc/parser.rb:22:in `parse'
	from /usr/src/app/lib/cc/engine/processed_source.rb:18:in `ast'
	from /usr/src/app/lib/cc/engine/analyzers/analyzer_base.rb:144:in `parse'
	from /usr/src/app/lib/cc/engine/analyzers/php/main.rb:29:in `process_file'
	from /usr/src/app/lib/cc/engine/analyzers/analyzer_base.rb:41:in `run'
	from /usr/src/app/lib/cc/engine/analyzers/reporter.rb:76:in `block in process_files'
	from /usr/src/app/lib/cc/engine/analyzers/file_thread_pool.rb:24:in `block (2 levels) in run'
/home/app/codeclimate-parser-client/lib/cc/parser/client.rb:86:in `run': (502) Bad gateway or gateway not responding (CC::Parser::Client::HTTPError)
	from /home/app/codeclimate-parser-client/lib/cc/parser.rb:22:in `parse'
	from /usr/src/app/lib/cc/engine/processed_source.rb:18:in `ast'
	from /usr/src/app/lib/cc/engine/analyzers/analyzer_base.rb:144:in `parse'
	from /usr/src/app/lib/cc/engine/analyzers/php/main.rb:29:in `process_file'
	from /usr/src/app/lib/cc/engine/analyzers/analyzer_base.rb:41:in `run'
	from /usr/src/app/lib/cc/engine/analyzers/reporter.rb:76:in `block in process_files'
	from /usr/src/app/lib/cc/engine/analyzers/file_thread_pool.rb:24:in `block (2 levels) in run'
```
Could someone please help me with this?

**Comment by milkshakeuk** [comment]
I have the same issue as this using code climate.
Is there a reason this was closed without an explanation?
How does one fix this issue?

**Comment by efueger** [comment]
Hi @milkshakeuk - this "Bad gateway" message is often a result of trying to access resources outside of your repository. (we often see this with vendored code, etc.)

Drop a line [here](https://codeclimate.com/help/new) and we'll be happy to take a closer look 👍🏼 

Thanks!

**Comment by milkshakeuk** [comment]
@efueger thank you, I have done that.
